server:
  port: 10200
spring:
  application:
    name: "LOGIN"
  datasource:
    url: jdbc:mysql://localhost:3306/myb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&allowPublicKeyRetrieval=true
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  redis:
    host: 192.168.56.129
    port: 6379
  cloud:
    # 配置sentinel
    sentinel:
      transport:
        # 控制台地址
        dashboard: 192.168.56.128
        port: 8718
      eager: true
    nacos:
      discovery:
        server-addr: 192.168.56.128:8848
        namespace: 12
# 开启sentinel声明式服务熔断
feign:
  sentinel:
    enabled: true

# 负载均衡配置
ribbon:
  MaxAutoRetries: 0 #（默认1次 不包括第一次）最大重试次数，当注册中心中可以找到服务，但是服务连不上时将会重试，如果注册中心中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 1 #（默认0次 不包括第一次）切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #（默认1s，即1000）请求连接的超时时间
  ReadTimeout: 5000 #（默认1s，即1000）请求处理的超时时间

captcha:
  width: 400
  height: 120
  codeCount: 6
  lineCount: 12